### ISSUE TITLE
Unable to open any saved .minder document, old or new

### ISSUE THREAD

**Issue by SimonBlancoE** [phase1geo/Minder#349]
After updating to version 1.12.2 I can't open any old .minder document. I've tried to uninstall and remove any remains of the app (except for my documents) and then install the most recent version from the AUR (I'm using Manjaro). I've also installed Minder in another laptop for the first time and send some of my documents over, getting the same result.

```
com.github.phase1geo.minder --version
1.12.2
```
I've tried to open the app firstly and then open a document from there. When I open the app I get these messages, but it starts anyway.

```
com.github.phase1geo.minder
I/O warning : failed to load external entity "/home/octo/.local/share/minder/favorites.xml"
I/O warning : failed to load external entity "/home/octo/.local/share/minder/exports.xml"
I/O warning : failed to load external entity "/home/octo/.local/share/minder/tab_state.xml"
```
When I try to open a .minder document from the app, it crashes, giving this message:

```
free(): invalid pointer
[1]    43736 abort (core dumped)  com.github.phase1geo.minder

```

If I try to open a .minder document by passing it as argument, I get the same result as above. 

I've tried to do this with documents saved before the update and new documents saved after the update. Same result. 

Additionally, when the program crashes, if won't start again unless I delete the contents of `~/.local/share/minder `

**Comment by wada3n** [comment]
Same issue with me too, occurred after an update today.

**Comment by MartineMin** [comment]
same problem with me. I can't open Neither minder , neither minder document. the program crashes

**Comment by phase1geo** [comment]
Can someone provide a .minder file that exhibits the issue?  I thought I had fixed the startup crash issue in 1.12.2.

**Comment by SimonBlancoE** [comment]
> Can someone provide a .minder file that exhibits the issue? I thought I had fixed the startup crash issue in 1.12.2. I'll get a new release made as soon as I can debug and fix the issue.

Here's one I made after the update: 
[mindertest.zip](https://github.com/phase1geo/Minder/files/6370410/mindertest.zip)

And one from before the update:
[LEGISLACIÓN-Notas-previas.zip](https://github.com/phase1geo/Minder/files/6370412/LEGISLACION-Notas-previas.zip)

**Comment by phase1geo** [comment]
I have pushed a fix to the master branch if someone wants to try running it on Manjaro.

**Comment by SimonBlancoE** [comment]
Cloned, installed and ran without problems. Thanks for the super fast fix. You're the man! 👏

**Comment by mochiballs** [comment]
Linux Mint 19.3 Trica, Cinnamon desktop
Minder version version 1.12.2 Flatpak install

Still unable to open .minder files. The application crashes right away if I try to opening it using the File/Open icon in the toolbar

**Comment by MartineMin** [comment]
Linux Ubuntu 20.04 . When i install Minder version 1.12.12 i have the message 
flatpak install flathub com.github.phase1geo.minder
Looking for matches…

com.github.phase1geo.minder permissions:
    ipc                   fallback-x11       wayland      x11
    file access [1]

    [1] xdg-documents


        ID                                 Branch Op Remote  Download
 1. [✓] com.github.phase1geo.minder.Locale stable i  flathub 27,7 kB / 366,7 kB
 2. [✓] com.github.phase1geo.minder        stable i  flathub 12,5 MB / 21,9 MB

Installation complete.
maison@maison-ZenBook-UX434FAC-UX433FAC:~$ flatpak run com.github.phase1geo.minder
Gtk-Message: 07:23:48.227: Failed to load module "canberra-gtk-module"
Gtk-Message: 07:23:48.227: Failed to load module "canberra-gtk-module"
I/O warning : failed to load external entity "/home/maison/.var/app/com.github.phase1geo.minder/data/minder/favorites.xml"
I/O warning : failed to load external entity "/home/maison/.var/app/com.github.phase1geo.minder/data/minder/exports.xml"
free(): invalid pointer
What is canberra-gtk-module ? 
What can I do ?
Thanks very much
Martine

**Comment by phase1geo** [comment]
The vala compiler (depending on version being used) has this weird code generator behavior where it frees memory when it should not in certain coding circumstances.  It doesn't generate any errors when parsing the code, indicating that the coding style is valid and will be handled without error, but then it does.  I have found/fixed several instances of this issue lately, but unfortunately, the version of valac that is being run to produce the flatpak for elementary from 1.12.2 contains other variants of this problem.  I will continue to look into and fix these issues, but what a pain in the butt this problem is for developers using the compiler...

**Comment by Vistavleal** [comment]
On fedora 34 the problem still exist. Can't launch minder if there is .minder files. I've install it using `dnf install minder`
```
$> com.github.phase1geo.minder --version
1.12.2
$> com.github.phase1geo.minder
I/O warning : failed to load external entity "/home/vellen/.local/share/minder/favorites.xml"
I/O warning : failed to load external entity "/home/vellen/.local/share/minder/exports.xml"
free(): invalid pointer
Aborted (core dumped)
```
Here is my .minder file.
[Main-Idea.zip](https://github.com/phase1geo/Minder/files/6502393/Main-Idea.zip)

**Comment by cybbro** [comment]
1.12.4 still fails to load .minder file on ubuntu 21.04, flatpak minder package.

**Comment by phase1geo** [comment]
Can you email me a .minder file which fails to load with the latest version? I want to take a look at it.

**Comment by cybbro** [comment]
> Can you email me a .minder file which fails to load with the latest version? I want to take a look at it.

I sent you the file, but I also opened it myself and I noticed that text is missing for some reason <Text> tags were all empty, so I went and restored older version of file from my backup, and it worked. But I have no clue why text is gone as this was first time I opened the .minder file with a text editor. So I guess, for some reason it's just damaged beyond repair, and other files work fine now.
