### ISSUE TITLE
Preferences dialog is not translatable

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#368]
All of Preferences.vala is missing a gettext macros to mark messages for translation. It's also the only place where you use 'make_label' :)

There are more cases where user-visible messages are not translatable. Should I report those separately?

**Comment by phase1geo** [comment]
I believe that I have fixed it in the master branch. Why don't you add the other missing translatable strings to this issue.

**Comment by phase1geo** [comment]
I have gone through all of the translatable strings in the source code. Hopefully, 1.12.4 is better.

**Comment by prokoudine** [comment]
So much better, thanks!

Still missing:

1. 'Enable animations' in the Preferences dialog
2. 'Select a node or connection to view/edit information' in the sidebar when no item is selected
3. All category names of stickers

**Comment by phase1geo** [comment]
I have fixed all of the above issues (I believe).  For the sticker categories and tooltips, I switched from loading this information via an XML resource to compiling the strings in a new helper class (called StickerSet).  I made a few attempts to get my XML file to be translatable, but didn't have luck so I used this method instead.  It should also slightly improve application startup performance since the sticker info doesn't need to be loaded since it it compiled into the application.

If you want to take a look, get the lastest from the master branch.  There's quite a few new small strings that will need to be translated.  Let me know if you see any additional issues.
