### ISSUE TITLE
The position-calculating function shows inexistent micro-changes of position on saving, confusing diff tools

### ISSUE THREAD

**Issue by ketsapiwiq** [phase1geo/Minder#503]
Hi!
First, thank you for this very useful and well-designed software, its minimalism made me not lose myself in options to manage my mindmaps.

So every time I open a Minder mindmap, and not even move it around (without even editing nodes), ask Git what changed in my repo, I end up having 2000+ (all) edited lines.
But when I look at it closer, I see what changed is **only the 15th decimal for the `posx`, `posy` and `treesize` properties** of nodes, since (I guess) the camera moved, (and eventually nodes position changed in relation to another?). It also seems to do it without even moving the camera, just because of a weird round function maybe?
ex:
```diff
-              <nodename posx="1023.0000000000006" posy="4373.1666666666679" maxwidth="200">
+              <nodename posx="1023.0000000000013" posy="4373.1666666666688" maxwidth="200">
                 <text data="example"/>
               </nodename>
               <nodenote></nodenote>
             </node>
-            <node id="275" posx="1009.0000000000006" posy="4429.1666666666715" width="151" height="70" side="right" fold="false" treesize="70" color="#c6262e" colorroot="false" layout="Horizontal" group="false">
+            <node id="275" posx="1009.0000000000013" posy="4429.1666666666688" width="151" height="70" side="right" fold="false" treesize="70" color="#c6262e" colorroot="false" layout="Horizontal" group="false">
```

This doesn't allow seeing meaningful info on which node has been edited / changed between two Minder files.

- would it be possible to make the "position calculating function" more deterministic? it seems to show ridiculous micro-changes in position (see example), showing everything as changed without even a click in Minder  
- or maybe not save (or not autosave) the position change of all nodes when the camera moves?
- or just allow for saving a more "basic" Minder file that strips out more optional info like position, to save only the most important elements of data structure? (helpful for comparing two versions)

I realize this last point is close to asking if the export can be automated in other formats.
It's true that if something along the lines of https://github.com/phase1geo/Minder/issues/493 gets implemented, I could only put a git config that says which program can be used for diffing `*.minder` files, and then for example it'll just compare the Markdown output of the two versions.

I guess the person in https://github.com/phase1geo/Minder/issues/482 has the same problem with Minder files tracked in Git, they will always appear as if everything in the file changed.

Thanks for reading,
Best,
Hadrien

**Comment by phase1geo** [comment]
After giving this some thought, I'm going to try doing something different with the canvas item placement such that scrolling around the mindmap won't modify the mindmap file itself.  However, if you close and then reopen the application, the mindmap will be displayed in the same way it was displayed prior to the close (this behavior is consistent with Elementary OS HIG).

I'll get working on this change shortly.

**Comment by phase1geo** [comment]
I have merged changes related to this request into the master branch.  I think there are still a few tweaks I need to make to improve the look of the initially loaded mind map (as it pertains to connection text).  There may be a few other minor issues related to this feature, but it works well enough as is.

**Comment by phase1geo** [comment]
Feel free to build the master branch and give the changes a try.

**Comment by ketsapiwiq** [comment]
Hi! I tried it by building the master branch (with Arch, I'm sure it contains the latest master commits), and the micro-changes still exist. If I just open it, scroll around, then immediately clause it, it won't show any diff, but any minor clicking (even if it results in no visible position change) would trigger all positions to be slightly modified.
Also, clicking the Save button without any edits or scroll still triggers the micro-changes.
I understand the format you're using might need to save each item's position. however, can't it be rounded to less that 15 decimals after the dot? (maybe only two decimals? maybe only one?)
Otherwise, for my `git diff` use case, https://github.com/phase1geo/Minder/issues/493 would also be an acceptable workaround.

Thanks a lot for your investment in this tool and its code!

**Comment by phase1geo** [comment]
I don't think that the master branch is picked up by any distribution, including Arch.  I'm recommending that to test the changes, pull the master branch from GitHub, build it and use it.  If you are loading an existing mindmap, you will need to save it, exit the application, and restart the application.  After doing all of this, you shouldn't be seeing any changes to the .minder file if you are only panning the canvas or changing the zoom factor.  The mindmap will only change when actual edits are made to the mindmap.

**Comment by phase1geo** [comment]
I don't think that the master branch is picked up by any distribution, including Arch.  I'm recommending that to test the changes, pull the master branch from GitHub, build it and use it.  If you are loading an existing mindmap, you will need to save it, exit the application, and restart the application.  After doing all of this, you shouldn't be seeing any changes to the .minder file if you are only panning the canvas or changing the zoom factor.  The mindmap will only change when actual edits are made to the mindmap.
