### ISSUE TITLE
Offset and cropped PNG export, offset PDF export, based on the scrolled position on canvas

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#553]
With version 1.15.2 (from Fedora 38, on GNOME Wayland and Xorg), on any mindmap, it seems export is based on the currently scrolled position (instead of the entire map's contents regardless of zoom/pan/scroll); I'm not sure if that is on purpose (I don't think it should be), but in any case it is quite problematic especially with issues like #551, where zoom (even the "Zoom fit" action) puts you into incontrollably off-set positions.

In the current situation, if I scroll down (with just the scroll wheel without any modifiers) the canvas, the PNG export will output something that is off-center with massively cut-off contents above or below; PDF export works slightly better as its boundaries are apparently less defined, but we can see it is still offset. Similarly, if I scroll up, to the sides, or use zoom (which currently messes with the position), it will result in differently offset/cropped exported files.

**Comment by phase1geo** [comment]
The last three issues that you have posted are all related to each other (along with issues related to zooming in on a subtree, centering a node on the screen, etc.)  The issue is related to changes made during 1.15 development where origin and scaling information were removed from the .minder file and stored elsewhere so that .minder files could be stored in git and used without causing file differences due to scrolling around in a mindmap (i.e., the tree itself is not changed only its view).

Unfortunately, there are still a few lingering issues due to this change that are being worked out in the 1.15.3 release work.  Stay tuned.

**Comment by nekohayo** [comment]
Thank you, and sorry if it was noisy on my part to be filing three issues for this, but I wasn't sure if it all boiled down to the exact same root cause or not, so I preferred to be specific and atomic in my reporting :)

**Comment by phase1geo** [comment]
No problem.  I would prefer that folks do this type of error reporting anyways even if they are linked to the same underlying cause.  Makes it easier to test out the fix for each error scenario.

**Comment by nekohayo** [comment]
A drive-by observation if I may, derived from a lot of weird occurrences, over the last few hours, of my maps going "all over the map" upon app restart: it seems like a big chunk of the problem is also affecting "connection" lines (the ones you create by pressing "X" with two nodes selected) in particular. Their midpoint position gets thrown into a different galaxy everytime you reposition something, sometimes in invisible ways (until you restart the app). It seems the relative positioning is particularly fragile when it comes to those "connection" lines. Perhaps you already know this, but I thought I'd mention it now because it's kind of a secondary feature that might be overlooked compared to the main branch lines.

I've had one weird situation just now where I thought the file had corrupt itself and lost all data, because on app restart I couldn't see anything at all in the canvas (it was all blank, no matter how I tried to pan or zoom out)... yet, the data _was_ in the .minder file, as exporting to Markdown proved. I couldn't figure out how to get past the seemingly blank canvas and restore the view to something usable (even if I suspected connection lines gone wild), until I renamed the filename and opened it from Nautilus, then it showed up fine, centered at 100% zoom level... apparently, opening it as a different file reset the canvas / forced it to ignore whatever zoom/panning there was.

**Comment by phase1geo** [comment]
The canvas "origin" and zoom level information has been moved to the ~/.local/share/minder/tab_state.xml file now. You can clear this issue up by either doing what you did or deleting this file. This file is used by Minder to remember the state of the tabs between Minder sessions, so you will only force Minder to forget that by deleting this file.

**Comment by phase1geo** [comment]
I believe that this issue is now fixed in 1.15.5.  Can you confirm that?

**Comment by TheRedCyclops** [comment]
I was able to reproduce this again in 1.17, deleting  ~/.local/share/minder/tab_state.xml fixed the problem, it seems like this isn't quite fixed yet @phase1geo

**Comment by phase1geo** [comment]
Which issue is not fixed in 1.17?

**Comment by TheRedCyclops** [comment]
When exporting the image was coming up offset and cropped, in all formats (tested png, pdf and svg)
