### ISSUE TITLE
Broken Style dock

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#670]
On beta1, the Style tab of the sidebar displays items at the bottom that I can't scroll to. I just see the top of the widgets, and the scrollbar doesn't let me go there. So I tried to collapse/expand other style groups, and this is what I'm now stuck with:

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/49c5a387-7efc-4e87-b9b0-9113ea38fe5e" />

It doesn't go away if I restart the program.

**Comment by phase1geo** [comment]
I have fixed the issue with the style sidebar expanders in the beta branch.  This fix will be a part of the 2.0.0-beta2 pre-release.

I'm not currently have any issues with scrolling the style sidebar.

**Comment by phase1geo** [comment]
Are you still having issues with scrolling the style sidebar?  I'm not seeing any issues with it on my end (I have a Fedora 42 VM that I'm testing with as well).  It's generally easier to scroll using a mouse by placing the cursor on the option labels as placing the mouse cursor over the style control area will sometimes stop scrolling the sidebar and instead scroll the control element.  Either that or move the cursor to the scrollbar area and when it widens, click and drag it up or down.

**Comment by prokoudine** [comment]
I've just rebuilt from git and I still can't scroll to the end:

<img width="2538" height="1440" alt="Image" src="https://github.com/user-attachments/assets/03005137-cd86-44a1-a1bb-d6ffb94efc91" />

**Comment by phase1geo** [comment]
Out of curiosity, the window screenshot above is lacking the right edge of the window.  Is the scrollbar showing it is at the bottom of its displayed content?  I'm not able to see the scrollbar in the image above.

I still can't replicate this problem, even on Fedora 42.  That has to be some sort of issue with the gtk4 scrolled window widget, but it seems odd that you are seeing this and I am not.

**Comment by phase1geo** [comment]
Does this problem still exist with the latest?  (2.0.5, I believe).

**Comment by prokoudine** [comment]
Seems to be fixed, thanks!
