### ISSUE TITLE
Node Alignment Issues with Manual Node Layout

### ISSUE THREAD

**Issue by MrDaisyBates** [phase1geo/Minder#680]
Fedora 43, 2.0 beta 5

<img width="499" height="1057" alt="Image" src="https://github.com/user-attachments/assets/c7eefc6a-1956-427b-9abc-0e0c2ee7ceb2" />

I flipped over to the "manual" node layout tab and this new alignment option presented itself. However, the buttons don't seem to respond nor have any intuitive markings on them from what I can see.

I also cannot find any information about this particular function/feature on the wiki, which makes me think it's new in 2.0 and undocumented.

**Comment by phase1geo** [comment]
These icons appear to be only available in the elementary icon set.  I will have a fix committed shortly.

**Comment by MrDaisyBates** [comment]
I have been messing around with this a little. It appears the buttons don't work for me at all, either. I mean, the icons are def missing. Idk if the icons being missing would also make the buttons unresponsive (I'm not a programmer in the slightest), but I could imagine that being a separate point. I just wanted to make sure to add that here.

**Comment by MrDaisyBates** [comment]
Fedora 43, Gnome, noob at self-compiling code

(If any of that assists you in working through this)

**Comment by phase1geo** [comment]
Node alignment buttons will be disabled unless two or more nodes are selected.  The node alignment buttons are used to align selected nodes in manual mode.  Selecting one or no nodes won't have an affect.

**Comment by phase1geo** [comment]
By the way, I have fixed the icon issue in the beta branch which will be available in beta-6.

**Comment by MrDaisyBates** [comment]
beta-6, I personally still don't have the icons. I did confirm that I can select two or more nodes and the buttons do seem to activate and do things (at first glance). 
<img width="577" height="146" alt="Image" src="https://github.com/user-attachments/assets/c00b95f7-9235-44a9-a0ca-03ce2ee80ee7" />
